#ifndef FANCY_DEFAULT_TRAITS_H
#define FANCY_DEFAULT_TRAITS_H

#define FANCY_TYPE_INFO_TRAIT_IMPLEMENTATIONS\
  IMPLEMENTATION(Rect)\
  IMPLEMENTATION(Circle)\
  IMPLEMENTATION(Geometry_Size)

#define FANCY_COMPARABLE_TRAIT_IMPLEMENTATIONS\
  IMPLEMENTATION(Geometry_Size)

#endif